version: 2.1
jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.54
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Run Hugo"
          command: |
            cd ~/project/blogs
            hugo --config config-prod.toml -v
      # - run:
      #     name: "Test Website"
      #     command: htmlproofer ~/project/blogs/public --allow-hash-href --check-html --empty-alt-ignore
      - run:
          name: Build and Deploy
          command: |
            echo "# install Azure CLI"
            apt-get update && apt-get install -y sudo
            echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ trusty main" | \
            sudo tee /etc/apt/sources.list.d/azure-cli.list
            curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
            sudo apt-get install apt-transport-https
            sudo apt-get update && sudo apt-get install azure-cli

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: 
                - master
                - test
