version: 2.1
jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.54
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Run Hugo"
          command: |
            cd ~/project/blogs
            hugo --config config-prod.toml -v
      # - run:
      #     name: "Test Website"
      #     command: htmlproofer ~/project/blogs/public --allow-hash-href --check-html --empty-alt-ignore
      - run:
          name: Install Azure CLI
          command: |
            echo "# install Azure CLI"
            apk update && \
              apk add bash py-pip && \
              apk add --virtual=build gcc libffi-dev musl-dev openssl-dev python-dev make && \
              pip --no-cache-dir install -U pip && \
              pip --no-cache-dir install azure-cli && \
              apk del --purge build
      - run:
          name: Deploy to Azure Blobs
          command: |
              az storage blob upload-batch --source ~/project/blogs/public --destination \$web --connection-string ${AZURE_STORAGE_CONNECTIONSTRING}

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: 
                - master
                - test
