baseURL = "https://blogs.precisionlender.com/"
languageCode = "en-us"
title = "LessThanDot Archive"
theme = "lessthandot"

disableKinds = ["RSS"]

[taxonomies]
  author = "author"
  tag = "tags"
  category = "categories"

[params]
googleAnalytics = "UA-4471405-1"
