baseURL = "https://blogs.lessthandot.com"
languageCode = "en-us"
title = "LessThanDot Archive"
theme = "lessthandot"

disableKinds = ["RSS"]

[taxonomies]
  author = "author"
  tag = "tags"
  category = "categories"

[params]
googleAnalytics = ""

