baseURL = "https://blogs.lessthandot.com/"
languageCode = "en-us"
title = "LessThanDot Archive"
theme = "lessthandot"

disableKinds = ["RSS"]

preserveTaxonomyNames = true

[taxonomies]
  author = "author"
  tag = "tags"
  category = "categories"

[params]
googleAnalytics = "G-WMQZ4JWS0V"

[markup.goldmark.renderer]
unsafe= true
